name = "cozy-soccer-champ"
main = "dist/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[observability.logs]
enabled = true


[env.production]
name = "cozy-soccer-champ-prod"

[env.staging]
name = "cozy-soccer-champ-staging"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "cozy-soccer-champ-db"
database_id = "065be909-9a91-4982-94e5-d5e44b3caf31"

# Environment variables will be set via wrangler secret put
[vars]
NODE_ENV = "production"
CORS_ORIGIN = "*"
LOG_LEVEL = "info"
PAGES_HOST = "cozzysoccerchamp.pages.dev"

# For storing sensitive variables, use:
# wrangler secret put SESSION_SECRET
# wrangler secret put TELEGRAM_BOT_TOKEN
# wrangler secret put FOOTBALL_API_TOKEN
# wrangler secret put TELEGRAM_ADMIN_CHAT_ID  # Optional: for backup notifications

# Cron jobs:
# - Database backups: daily at 03:00 UTC
# - Live score sync: every 3 minutes (during match days)
[triggers]
crons = [
  "0 3 * * *",      # Daily backup at 03:00 UTC
  "*/3 * * * *"     # Live sync every 3 minutes
]

# R2 bucket for storing backups
[[r2_buckets]]
binding = "BACKUP_BUCKET"
bucket_name = "cozy-soccer-backups"
